batch_size: 8
conf_threshold: 0.25
copy_paste: 0.0
degrees: 0
epochs: 50
fliplr: 0.5
flipud: 0.0
hsv_h: 0
hsv_s: 0
hsv_v: 0.3
imgsz: 640
iou_threshold: 0.45
learning_rate: 0.01
mixup: 0.1
model_size: yolov8n.pt
mosaic: 0.5
patience: 10
perspective: 0.0
scale: 0.2
shear: 0
translate: 0.1
warmup_epochs: 3
